algoritmo "Acumuladores"
var
   soma, n: inteiro
inicio
   soma <- 0
   escreval ("Digite um número: ")
   leia (n)
   soma <- soma + n
   
   escreval ("Digite um número: ")
   leia (n)
   soma <- soma + n
   
   escreval ("Digite um número: ")
   leia (n)
   soma <- soma + n
   
   escreval ("Digite um número: ")
   leia (n)
   soma <- soma + n
   
   escreval
   escreva ("A soma dos 4 números é: ", soma)
fimalgoritmo