algoritmo "Exercicio 3"
var
   nome: Caractere
   salario: caractere
inicio
      Escreva ("Digite o nome completo do funcionário: ")
      Leia (nome)
      Escreva ("Digite o salário do funcionário: ")
      Leia (salario)
      Escreval("Nome do funcionário: ", nome)
      Escreval("Salário: ", salario)
      Escreval("O funcionário ", nome ," tem um salário de R$", salario, " em Junho.")
fimalgoritmo
