algoritmo "Procedimento linha"
var
    x: inteiro
procedimento fazerLinhas( n: inteiro)
var //variaveis locais se existirem
    x: inteiro
inicio // corpo do procedimeto local
    para x de 1 ate n faca
    escreval("____   ____   ____   ____   ____   ____")
    fimpara
fimprocedimento


//Programa principal
inicio
    
    //para x de 1 ate 30 faca
    //   fazerLinhas
    //fimpara
    
    fazerLinhas(50)
fimalgoritmo