algoritmo "Tinturametroquadrado"
var
   altura, largura, area, quantidade: Real
inicio
   Escreva("Digite a altura da sua parede: ")
   Leia(altura)
   Escreval("Digite a largura da sua parede: ")
   leia(largura)
   area <- altura * largura
   EScreval ("A area a ser pintada é de ", area)
   quantidade <- area / 2
   EScreval("A quantidade de tinta a ser utilizada em sua parede é de ", quantidade)
fimalgoritmo